# This config file is meant for settings that affect your whole activity list, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Activities for a BetterMTL

# What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Activities

description: Montrealers team up, better city

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bettermtl.github.io" # the base hostname & protocol for your site

author: Paul Cuciureanu
twitter_username: pcuci
github_username:  bettermtl
company_name: BetterMTL

# Build settings
markdown: kramdown

# Show future posts for future events.
future: true

permalink: /event/:title.html
